// Minimal FHIR R4 read API over the Jovi data model. Auth: Firebase ID token of an active staff member
// (Authorization: Bearer <idToken>). Resources: Patient, Condition, MedicationRequest, Observation, Immunization, Encounter, AllergyIntolerance.
// GET /fhir/metadata · /fhir/Patient/{uid} · /fhir/{Resource}?patient={uid}
const functions = require('firebase-functions/v1');
const admin = require('firebase-admin');
if (!admin.apps.length) admin.initializeApp();
const db = () => admin.firestore();
const ts = v => (v && v.toDate ? v.toDate().toISOString() : (typeof v === 'string' ? v : null));

async function auth(req) {
  const m = (req.get('Authorization') || '').match(/^Bearer (.+)$/); if (!m) return null;
  try { const t = await admin.auth().verifyIdToken(m[1]); const s = await db().doc(`staff/${t.uid}`).get(); if (!s.exists || s.data().active === false) return null; return { uid: t.uid, role: s.data().role }; } catch { return null; }
}
const bundle = (entries, total) => ({ resourceType: 'Bundle', type: 'searchset', total: total ?? entries.length, entry: entries.map(r => ({ resource: r })) });
const patientRes = (uid, u) => ({ resourceType: 'Patient', id: uid, identifier: [{ system: 'urn:jovi:member', value: uid }], active: (u.subscriptionStatus || 'active') !== 'canceled', name: [{ text: u.onboard_fullName || [u.first || u.firstName, u.last || u.lastName].filter(Boolean).join(' ') }], telecom: [u.email ? { system: 'email', value: u.email } : null, (u.phone || u.onboard_phone) ? { system: 'phone', value: u.phone || u.onboard_phone } : null].filter(Boolean), gender: (u.gender || u.onboard_gender || '').toLowerCase() || undefined, birthDate: u.onboard_birth || u.birth || u.dob || undefined, address: (u.address || u.city) ? [{ line: [u.address || u.onboard_address].filter(Boolean), city: u.city, state: u.state, postalCode: u.zip }] : undefined });

exports.fhir = functions.https.onRequest(async (req, res) => {
  res.set('Content-Type', 'application/fhir+json');
  if (req.path.replace(/^\/fhir/, '') === '/metadata') return res.json({ resourceType: 'CapabilityStatement', status: 'active', fhirVersion: '4.0.1', format: ['json'], rest: [{ mode: 'server', resource: ['Patient', 'Condition', 'MedicationRequest', 'Observation', 'Immunization', 'Encounter', 'AllergyIntolerance'].map(type => ({ type, interaction: [{ code: 'read' }, { code: 'search-type' }] })) }] });
  const who = await auth(req); if (!who) return res.status(401).json({ resourceType: 'OperationOutcome', issue: [{ severity: 'error', code: 'login', diagnostics: 'Staff bearer token required' }] });
  const parts = req.path.replace(/^\/fhir\/?/, '').split('/').filter(Boolean); const type = parts[0]; const id = parts[1]; const pid = id || req.query.patient;
  if (!pid) return res.status(400).json({ resourceType: 'OperationOutcome', issue: [{ severity: 'error', code: 'required', diagnostics: 'patient parameter required' }] });
  const uSnap = await db().doc(`users/${pid}`).get(); if (!uSnap.exists) return res.status(404).json({ resourceType: 'OperationOutcome', issue: [{ severity: 'error', code: 'not-found' }] });
  const u = uSnap.data(); const subj = { reference: `Patient/${pid}` };
  await db().collection('audit_logs').add({ action: 'fhir.read', target: `users/${pid}`, meta: { type }, staffId: who.uid, role: who.role, at: admin.firestore.FieldValue.serverTimestamp() });
  const rows = async (path, ...q) => { let ref = db().collection(path); for (const [f, op, v] of q) ref = ref.where(f, op, v); const s = await ref.limit(500).get(); return s.docs.map(d => ({ id: d.id, ...d.data() })); };
  switch (type) {
    case 'Patient': return res.json(id ? patientRes(pid, u) : bundle([patientRes(pid, u)]));
    case 'Condition': { const p = await rows(`users/${pid}/problems`); return res.json(bundle(p.map(x => ({ resourceType: 'Condition', id: x.id, subject: subj, clinicalStatus: { coding: [{ code: x.status === 'active' ? 'active' : 'resolved' }] }, code: { coding: x.icdCode ? [{ system: 'http://hl7.org/fhir/sid/icd-10-cm', code: x.icdCode, display: x.label }] : [], text: x.label }, onsetDateTime: x.onset || undefined, recordedDate: ts(x.createdAt) })))); }
    case 'MedicationRequest': { const p = await rows('prescriptions', ['userId', '==', pid]); return res.json(bundle(p.map(x => ({ resourceType: 'MedicationRequest', id: x.id, subject: subj, status: x.status === 'active' ? 'active' : x.status === 'discontinued' ? 'stopped' : 'completed', intent: 'order', medicationCodeableConcept: { text: [x.medicationName, x.strength].filter(Boolean).join(' ') }, dosageInstruction: [{ text: [x.dosage, x.frequency, x.instructions].filter(Boolean).join(' · ') }], dispenseRequest: { numberOfRepeatsAllowed: x.totalRefills || 0, expectedSupplyDuration: x.daysSupply ? { value: x.daysSupply, unit: 'days' } : undefined }, authoredOn: ts(x.prescribedAt || x.createdAt), requester: { display: x.prescribedBy || '' } })))); }
    case 'Observation': { const v = await rows(`users/${pid}/vital_signs`); const l = await rows(`users/${pid}/lab_results`); const obs = [...v.map(x => ({ resourceType: 'Observation', id: x.id, subject: subj, status: 'final', category: [{ coding: [{ code: 'vital-signs' }] }], code: { text: x.type }, effectiveDateTime: ts(x.timestamp), ...(x.type === 'Blood Pressure' ? { component: [{ code: { text: 'Systolic' }, valueQuantity: { value: x.systolic, unit: 'mmHg' } }, { code: { text: 'Diastolic' }, valueQuantity: { value: x.diastolic, unit: 'mmHg' } }] } : { valueQuantity: { value: x.value, unit: x.unit } }) })), ...l.map(x => ({ resourceType: 'Observation', id: x.id, subject: subj, status: 'final', category: [{ coding: [{ code: 'laboratory' }] }], code: { text: x.testName }, effectiveDateTime: ts(x.resultedAt), valueString: `${x.value} ${x.unit || ''}`.trim(), referenceRange: x.referenceRange ? [{ text: x.referenceRange }] : undefined, interpretation: x.flag ? [{ text: x.flag }] : undefined }))]; return res.json(bundle(obs)); }
    case 'Immunization': { const p = await rows(`users/${pid}/vaccinations`); return res.json(bundle(p.map(x => ({ resourceType: 'Immunization', id: x.id, patient: subj, status: 'completed', vaccineCode: { text: x.vaccineName }, occurrenceDateTime: ts(x.administeredAt), lotNumber: x.lotNumber || undefined, performer: x.provider ? [{ actor: { display: x.provider } }] : undefined, note: x.doseLabel ? [{ text: x.doseLabel }] : undefined })))); }
    case 'Encounter': { const p = await rows(`users/${pid}/visit_records`); return res.json(bundle(p.map(x => ({ resourceType: 'Encounter', id: x.id, subject: subj, status: x.signedAt ? 'finished' : 'in-progress', class: { code: /tele/i.test(x.type || '') ? 'VR' : 'AMB' }, type: [{ text: x.type }], period: { start: ts(x.visitDate) }, reasonCode: x.chiefComplaint ? [{ text: x.chiefComplaint }] : undefined, participant: x.providerName ? [{ individual: { display: x.providerName } }] : undefined, diagnosis: (x.diagnoses || []).map(d => ({ condition: { display: d.label } })) })))); }
    case 'AllergyIntolerance': { const list = Array.isArray(u.allergies) ? u.allergies : (u.allergies ? String(u.allergies).split(/,|;/).map(s => s.trim()).filter(Boolean) : []); return res.json(bundle(list.map((a, i) => ({ resourceType: 'AllergyIntolerance', id: `${pid}-${i}`, patient: subj, clinicalStatus: { coding: [{ code: 'active' }] }, code: { text: a } })))); }
    default: return res.status(404).json({ resourceType: 'OperationOutcome', issue: [{ severity: 'error', code: 'not-supported', diagnostics: `Unsupported resource ${type}` }] });
  }
});
