"""Editorial content for the national cost guides.  JC-LAZO-COST-0916-001

One entry per taxonomy category; generate/templates/cost_guide.html renders it at
/cost/<slug>/. This is the top-of-funnel layer the site did not have: /for-vendors/
and the comparison pages answer "which platform", and metro/category pages answer
"who is available" - but nobody arrives at either until they already know what they
want. "How much does a wedding photographer cost" is asked first, by far more people,
and until now we had no page for it.

RANGES MUST AGREE WITH config/pricing.py. Those FAQs are already rendered on ~72,000
vendor pages; a guide that quotes a different number for the same category makes both
look invented. pricing.py stays the source of truth for the per-metro FAQ, this file
expands the same figures into a page. If you change one, change the other.

Every range here is phrased as what couples actually pay, not a quote we are
promising on a vendor's behalf. We do not yet hold verified booking data - when we
do (vendors publishing packages, couples confirming spend), these become
evidence-backed and the per-metro versions become worth building. Until then this
is honest market guidance and is written to read as such.

Schema per category:
  question the search itself, used as the h1 and title - NOT the taxonomy noun.
           Nobody googles "wedding stationer cost"; they google "wedding
           invitations cost". The taxonomy exists to sort vendors, not to
           phrase a question, and these pages live or die on matching the query.
  short    that category's noun for inline use ("every wedding florist sets...")
  hook     one line for the /cost/ hub card - the most useful thing we know
  answer   one-paragraph direct answer - the thing the search was asking
  typical  the headline range, repeated in the hero and the schema
  bands    3 x (label, range, what that money actually buys)
  drivers  (what moves the price, why) - the part most cost articles skip
  save     (how to spend less, what it costs you) - honest trade-offs, not "DIY it"
  ask      questions that change the quote or prevent a bad booking
  timing   when to book, and what happens if you are late
  faqs     rendered as FAQPage schema; keep answers self-contained
"""

GUIDES = {
    # ---------------------------------------------------------------- photo/video
    "wedding-photographers": {
        "question": 'How much does a wedding photographer cost?',
        "short": 'wedding photographer',
        "hook": 'Hours of coverage matter more than the package name.',
        "typical": "$1,500-$3,500",
        "answer": "Most couples pay between $1,500 and $3,500 for wedding photography. Below that you are usually buying fewer hours or a newer shooter; above it you are buying a second photographer, an album, and someone whose calendar fills a year out. The number that actually matters is not the package price but the price per hour of coverage, because that is the line most couples end up wishing they had bought more of.",
        "bands": [
            ("Under $1,500", "$800-$1,500",
             "Typically 4-6 hours, one photographer, digital files only. Often someone in their first two or three seasons. Real work gets made at this price - but 6 hours usually means coverage starts at the ceremony, so getting ready and the end of the reception are not photographed."),
            ("What most couples pay", "$1,500-$3,500",
             "6-8 hours, one experienced photographer, sometimes a second shooter at the top of the band, and 400-800 edited images. This is the range where you are choosing on style rather than on who is available."),
            ("Premium", "$3,500-$10,000+",
             "Full-day coverage, a second shooter as standard, engagement session, album, and often a team with an editor and an assistant. At the top of this band you are booking a name, and the calendar is the constraint, not the budget."),
        ],
        "drivers": [
            ("Hours of coverage", "The single biggest lever. Every extra hour is typically $250-$500, and the hours couples regret cutting are always the last ones - the dancing, the send-off, the part of the night nobody was posing for."),
            ("A second shooter", "Usually $300-$600. Buys you the other angle: your partner getting ready while you get ready, the aisle reaction while the ceremony is shot from the front. On weddings over about 120 guests it stops being optional."),
            ("Experience and demand", "A photographer in their eighth season prices differently from one in their second, and both may be excellent. What you pay for with experience is consistency in bad light and bad weather, and someone who has seen your venue before."),
            ("Season and day", "Peak-season Saturdays cost the most because they sell out first. A Friday or Sunday in your area's off-season commonly saves 10-25% on the same photographer."),
            ("Albums and prints", "A designed album is typically $600-$1,500. Many couples buy it a year later, which is fine - just confirm the price is held."),
            ("Travel", "Beyond roughly an hour from their base, expect mileage, and beyond about three hours expect a night's accommodation."),
        ],
        "save": [
            ("Buy hours, not extras",
             "If you have to cut, cut the engagement session and the album before you cut coverage hours. You can buy an album any time; you cannot re-shoot the reception."),
            ("Move the date, not the photographer",
             "The same photographer on a Friday, a Sunday, or in your off-season is often 10-25% less. This is the only lever that costs you nothing in quality."),
            ("Shorten the day, deliberately",
             "A tight 6-hour timeline that starts at hair-and-makeup and ends after the first dances captures more of the wedding than 8 loose hours with a long gap in the middle. Ask your photographer to help you build it."),
            ("Skip the second shooter only if the day is small",
             "Under about 80 guests in one venue, one strong photographer covers it. A two-location day or a big guest list is where a solo shooter starts missing things."),
        ],
        "ask": [
            "Can I see two complete galleries from real weddings - not highlight selections - ideally one shot at a venue like mine?",
            "Who is actually photographing my wedding, and is their name in the contract?",
            "How many edited images will I receive, and by what date?",
            "What happens if you are ill or have an emergency on the day?",
            "Are the files delivered at full resolution, and do I have permission to print them?",
        ],
        "timing": "Photographers with strong reputations are commonly booked 9-14 months ahead, and peak-season Saturdays go first. If your date is inside six months, do not assume you have missed out - ask about waitlists and cancellations, because openings genuinely do appear.",
        "faqs": [
            ("How much does a wedding photographer cost?",
             "Most couples pay $1,500 to $3,500 for wedding photography. Under $1,500 usually means fewer hours or a newer photographer; above $3,500 typically adds a second shooter, an album, and full-day coverage. Hours of coverage is the biggest single factor in the price."),
            ("How many hours of wedding photography do we need?",
             "Six to eight hours covers most weddings from the end of getting ready through the first dances. Eight to ten hours is more comfortable if you want detailed getting-ready coverage or a late send-off, or if your ceremony and reception are at different venues."),
            ("Is a second shooter worth it?",
             "On weddings over roughly 120 guests, or any day with two locations, yes - it is the difference between one angle and two, and it is the only way to photograph both partners getting ready. For a small single-venue wedding, one experienced photographer is usually enough."),
            ("How far in advance should we book a wedding photographer?",
             "Nine to fourteen months ahead is typical, and sooner for a peak-season Saturday. Inside six months, ask about cancellations rather than assuming you are too late."),
        ],
    },
    "wedding-videographers": {
        "question": 'How much does a wedding videographer cost?',
        "short": 'wedding videographer',
        "hook": 'The thing couples most often wish they had bought.',
        "typical": "$1,200-$2,500",
        "answer": "Wedding films typically run $1,200 to $2,500 for core coverage - usually a highlight film of three to eight minutes plus the ceremony filmed in full. Premium packages add a longer feature edit, drone work, and same-day edits. Video is the single most common thing couples say they wish they had bought, which is worth knowing before you cut it.",
        "bands": [
            ("Under $1,200", "$700-$1,200",
             "A short highlight film, one operator, limited hours. Often excellent work from someone building a reel. Ask specifically how audio is captured - this is the band where vows sometimes arrive unusable."),
            ("What most couples pay", "$1,200-$2,500",
             "Highlight film plus full ceremony and speeches, one or two operators, properly mic'd audio, delivered in 6-12 weeks."),
            ("Premium", "$2,500-$6,000+",
             "Two or three operators, a documentary-length feature alongside the highlight, drone, and sometimes a same-day edit played at the reception."),
        ],
        "drivers": [
            ("Number of operators", "One camera cannot be on the vows and the reaction at the same time. A second operator is typically $400-$800 and is what makes a ceremony edit feel like it was filmed rather than recorded."),
            ("Edit length and complexity", "A 4-minute highlight is a different amount of work from a 45-minute feature. Colour grading and licensed music sit here too."),
            ("Audio", "Good wedding film is an audio product as much as a visual one. Lapel mics on the officiant and both partners, plus a board feed at the reception, is what separates a film you rewatch from one you do not."),
            ("Drone", "Usually $200-$500 where it is legal to fly. Check your venue allows it - many do not."),
            ("Delivery speed", "A same-day edit shown at the reception is a premium add-on because it means an editor working on site through your wedding."),
        ],
        "save": [
            ("Take the shorter film, not no film",
             "If the budget forces a choice, a 3-minute highlight at $900 beats nothing at all. This is the decision couples most often revisit."),
            ("Book photo and video together",
             "Many studios that offer both discount the pair, and a team that already works together needs less choreography on the day."),
            ("Drop the drone before you drop the second operator",
             "Aerial footage is lovely and nobody has ever cried at it."),
            ("Ask about ceremony-and-speeches-only",
             "Some videographers offer a documentary package with no highlight edit at a lower price. You get the whole ceremony and every toast, unedited - which is what most families actually rewatch."),
        ],
        "ask": [
            "How is audio captured - who gets mic'd, and do you take a feed from the DJ or band?",
            "Can I watch a full ceremony edit, not just a highlight reel?",
            "How long until delivery, and what is the music licensing situation?",
            "Do you work alongside my photographer, and have you two worked together before?",
            "What is your backup plan for a failed card or camera?",
        ],
        "timing": "Book 8-12 months out. Videographers are usually available later than photographers because fewer couples book video at all - so if you are inside six months, this is often the easier of the two to still get.",
        "faqs": [
            ("How much does a wedding videographer cost?",
             "Most couples pay $1,200 to $2,500 for wedding videography covering a highlight film plus the full ceremony. Budget options start near $700 for a short highlight; premium packages with multiple operators, a feature-length edit and drone work run $2,500 to $6,000 or more."),
            ("Do we need both a photographer and a videographer?",
             "They do different jobs. Photographs are how you will display the day; film is how you will hear it - the vows, the toasts, your grandmother's voice. Couples who skip video name it their most common regret, so if budget forces a choice, consider a shorter film rather than none."),
            ("How long does a wedding video take to arrive?",
             "Six to twelve weeks is normal for a highlight film; feature-length edits often take longer. Same-day edits are a premium service delivered at the reception itself. Get the delivery date in the contract."),
        ],
    },
    # ---------------------------------------------------------------- the big line
    "wedding-venues": {
        "question": 'How much does a wedding venue cost?',
        "short": 'wedding venue',
        "hook": 'The rental fee is almost never the real number.',
        "typical": "$3,000-$15,000+",
        "answer": "Wedding venues span more than any other category - roughly $3,000 for a simple space up to $15,000 and well beyond for full-service estates and resorts. The advertised rental fee is rarely the real number. What matters is total cost once you add what is required: mandated caterers, food and beverage minimums, service charges, and everything the venue does not include but does not let you bring.",
        "bands": [
            ("Simple spaces", "$1,500-$5,000",
             "Community halls, parks, restaurants, small event spaces, and many all-inclusive weekday packages. You typically bring in everything, which means the rental fee is genuinely only the start."),
            ("What most couples pay", "$5,000-$12,000",
             "Dedicated wedding venues, barns, vineyards, hotels. Usually includes tables, chairs and some staffing, and often carries a food and beverage minimum rather than a flat rental."),
            ("Premium", "$12,000-$40,000+",
             "Estates, resorts, historic buildings and destination properties. Frequently full-service with in-house catering, and priced on a minimum spend that scales with your guest count."),
        ],
        "drivers": [
            ("Guest count", "Almost everything at a venue is per-person once you are inside it. Twenty fewer guests is usually a bigger saving than any negotiation."),
            ("Food and beverage minimums", "Many venues charge little or no rental but require you to spend a set amount on catering and bar. Compare venues on minimum spend, never on rental fee."),
            ("Service charge and admin fees", "Commonly 18-24% on top of food and beverage, and sometimes on rental too. This is not gratuity and it is not optional - ask for it as a number, not a percentage."),
            ("What is genuinely included", "Tables, chairs, linens, china, staffing, setup and strike, and a coordinator are each worth $500-$3,000 if you have to rent them separately. A more expensive venue that includes them is often cheaper overall."),
            ("Date and day", "Peak Saturdays cost the most. The same venue on a Friday, a Sunday, or in the off-season is routinely 20-40% less."),
            ("Vendor restrictions", "An exclusive caterer list removes your ability to shop that line. Sometimes the in-house option is good value; sometimes it is the venue's margin."),
        ],
        "save": [
            ("Compare total cost, not rental fee",
             "Build a spreadsheet with rental, minimum spend, service charge, and everything you would have to rent separately. Venues reorder dramatically once you do this, and it is the single most valuable hour of wedding planning."),
            ("Move off Saturday",
             "A Friday or Sunday at the same venue commonly saves 20-40%. Off-season saves again. Nobody has ever remembered which day of the week a wedding was."),
            ("Cut the guest list before you cut anything else",
             "Every guest carries catering, bar, rentals, invitations and cake. Twenty fewer people often saves more than changing venue."),
            ("Ask what they will throw in rather than discount",
             "Venues protect their headline rate but will often include ceremony space, an extra hour, upgraded linens or parking. Ask for value, not a lower number."),
        ],
        "ask": [
            "What is the total cost for my guest count - rental, minimum spend, service charge and tax, as one number?",
            "What exactly is included, and what will I have to rent separately?",
            "What is the rain plan, and at what time do I have to call it?",
            "When can my vendors load in, and what are the overtime charges?",
            "Are we the only wedding that day, and who from your team will be there?",
        ],
        "timing": "Venues are booked first and set your date, so start 12-18 months out - and understand that for a peak Saturday you are choosing between available dates, not choosing a date and then a venue. Everything else in this guide follows from what you sign here.",
        "faqs": [
            ("How much does a wedding venue cost?",
             "Venue costs range from about $1,500 for simple spaces to $40,000 or more for estates and resorts, with most couples paying $5,000 to $12,000. The rental fee is often misleading - compare venues on total cost including food and beverage minimums, service charges, and anything you would have to rent separately."),
            ("What is a food and beverage minimum?",
             "A required amount you must spend on catering and bar, separate from or instead of a rental fee. A venue with no rental fee and a $12,000 minimum is more expensive than one charging $4,000 rental with no minimum, unless you were going to spend that on food anyway."),
            ("How far in advance should we book a wedding venue?",
             "Twelve to eighteen months for a peak-season Saturday. The venue sets your date and most other vendors cannot be booked until it is confirmed, so this is the first booking to make."),
            ("Is a weekday wedding really cheaper?",
             "Yes, typically 20-40% at the same venue, and often with better availability among your other vendors too. Friday evenings and Sundays are the most popular alternatives to Saturday."),
        ],
    },
    "wedding-planners": {
        "question": 'How much does a wedding planner cost?',
        "short": 'wedding planner',
        "hook": 'Three tiers, and the industry uses the words inconsistently.',
        "typical": "$800-$4,500+",
        "answer": "Wedding planning is priced in three tiers, and the words are used inconsistently across the industry. Day-of coordination commonly runs $800 to $2,000, partial planning $2,000 to $4,500, and full-service planning usually starts around $4,500 and scales with the size of the wedding. Many planners save couples more than their fee through vendor relationships and avoided mistakes - but that is an argument for hiring one, not a reason to skip comparing them.",
        "bands": [
            ("Day-of coordination", "$800-$2,000",
             "A misleading name: good coordinators start 4-6 weeks out, confirm every vendor, build the timeline, run the rehearsal, and manage the day itself. What it does not include is help choosing vendors or designing anything."),
            ("Partial planning", "$2,000-$4,500",
             "Coordination plus vendor recommendations and booking help, usually starting a few months out. The right tier for couples who have a venue and a vision but not the time."),
            ("Full-service planning", "$4,500-$15,000+",
             "From engagement to send-off: budget, venue search, every vendor, design, and the day. Often priced as a percentage of total spend (10-15%) on larger weddings."),
        ],
        "drivers": [
            ("Scope, not hours", "The gap between coordination and full planning is months of work, not a longer wedding day. Be honest about which one you actually want."),
            ("Guest count and complexity", "A 200-guest wedding across two venues with a weekend of events is a different job from 80 guests in one room."),
            ("Percentage-based pricing", "Common on larger weddings and worth understanding: at 12% of spend, a $90,000 wedding means a $10,800 fee. Ask whether the percentage applies to the whole budget including the venue."),
            ("Design services", "Styling, mood boards, renderings and installation oversight are frequently a separate line from planning."),
            ("Team size on the day", "One coordinator can run a small wedding. Two hundred guests with a complex timeline usually needs an assistant, typically $300-$600."),
        ],
        "save": [
            ("Buy coordination even if you plan it yourself",
             "The cheapest tier is the one almost nobody regrets. Without it, the person running your wedding is your mother, your maid of honour, or you."),
            ("Do not pay for design you already have",
             "If you know exactly what you want, partial planning with your own aesthetic costs less than full service and gets you the same day."),
            ("Ask about a fixed fee instead of a percentage",
             "On a larger budget, a flat fee can be substantially less than 10-15% - and it removes the awkward incentive to spend more."),
            ("Check what your venue coordinator actually does",
             "Some venues include real coordination. Most include someone who manages the building, not your wedding. Get the distinction in writing before deciding you are covered."),
        ],
        "ask": [
            "Which tier is this, and precisely what is and is not included?",
            "How many weddings do you take on my date and that weekend?",
            "Do you work for me or does the venue pay you anything?",
            "Who will actually be on site, and will I have met them before the day?",
            "Do you take commissions or kickbacks from vendors you recommend?",
        ],
        "timing": "Full-service planners are booked 12-18 months out, often before the venue, because helping you choose the venue is part of the job. Day-of coordinators can frequently be booked 4-6 months out, though the good ones go earlier.",
        "faqs": [
            ("How much does a wedding planner cost?",
             "Day-of coordination typically costs $800 to $2,000, partial planning $2,000 to $4,500, and full-service planning usually starts around $4,500 and rises with the size of the wedding. Larger weddings are often priced at 10-15% of total spend."),
            ("What is the difference between a planner and a venue coordinator?",
             "A venue coordinator works for the venue and is responsible for the venue's obligations - the building, its staff, its timeline. A planner works for you, across every vendor and the whole day. Most couples need at least a day-of coordinator even at venues with excellent staff."),
            ("Is a wedding planner worth the money?",
             "The strongest case is for day-of coordination, which is the cheapest tier and the one couples most regret skipping - without it, someone you love spends your wedding working. Full-service planning is worth it when you lack time rather than taste."),
            ("What does 'day-of' coordination actually include?",
             "Despite the name, good day-of coordination usually begins 4-6 weeks before the wedding: confirming every vendor, building and distributing the timeline, running the rehearsal, and managing the wedding day itself."),
        ],
    },
    # ---------------------------------------------------------------- music
    "wedding-djs": {
        "question": 'How much does a wedding DJ cost?',
        "short": 'wedding DJ',
        "hook": 'Pay for the MC skill, not the song list.',
        "typical": "$1,000-$2,000",
        "answer": "Most couples spend $1,000 to $2,000 on a wedding DJ, typically covering five to six hours, a sound system, and MC duties. The thing that separates a good wedding DJ from a bad one is not the music library - it is whether they can read a room and make announcements without making everyone wince. Ask about the MC skill at least as hard as you ask about the playlist.",
        "bands": [
            ("Under $1,000", "$500-$1,000",
             "Usually a newer DJ or a part-time operator, 4-5 hours, basic sound. Fine for a small reception; ask specifically who handles announcements."),
            ("What most couples pay", "$1,000-$2,000",
             "5-6 hours, professional sound sized to the room, wireless mics for the ceremony and toasts, MC duties, and a planning call to go through your must-plays and do-not-plays."),
            ("Premium", "$2,000-$4,000+",
             "Named DJs in demand, full lighting design, multiple zones (ceremony, cocktail, reception), backup equipment on site, and sometimes a second attendant."),
        ],
        "drivers": [
            ("Hours and zones", "Ceremony audio in one place, cocktails in another and a reception in a third means three setups, not one."),
            ("Lighting", "Uplighting is commonly $300-$800; dance-floor and monogram lighting more. It changes photographs more than people expect."),
            ("Ceremony sound", "Often a separate line, typically $200-$400, and worth every cent - unamplified outdoor vows are the most common audio failure at weddings."),
            ("MC involvement", "Some DJs only play music. If you want announcements, introductions and flow management, confirm it is included."),
            ("Add-ons", "Photo booths, cold sparks, dancing on clouds - each typically $300-$900."),
        ],
        "save": [
            ("Pay for the MC, skip the sparks",
             "Effects are memorable for ten seconds. A DJ who keeps the night moving is what people describe afterwards as a great wedding."),
            ("Bundle ceremony, cocktail and reception",
             "Buying all three from one DJ is nearly always cheaper than a separate ceremony sound rental."),
            ("Trim uplighting rather than cutting it",
             "Eight fixtures around the room does most of the work of twenty."),
            ("Do not hand a friend an aux cable",
             "The saving is real and so is the risk: no backup, no mic technique, and nobody to tell 200 people where to go next."),
        ],
        "ask": [
            "Will you be the DJ at my wedding, or does your company assign someone later?",
            "Are you MCing as well as playing, and can I hear you on a mic?",
            "How do you handle requests, and will you play from my do-not-play list under any circumstances?",
            "What backup equipment do you bring?",
            "Is ceremony and cocktail-hour sound included or separate?",
        ],
        "timing": "Six to nine months out is typical, though in-demand DJs go a year ahead for peak Saturdays. This is one of the easier categories to fill late.",
        "faqs": [
            ("How much does a wedding DJ cost?",
             "Most couples pay $1,000 to $2,000 for a wedding DJ covering five to six hours with sound and MC duties. Budget options start around $500; premium DJs with full lighting design and multiple sound zones run $2,000 to $4,000 or more."),
            ("Should we have a DJ or a live band?",
             "A DJ costs roughly a third of a band, plays every song exactly as people know it, and handles announcements. A band brings energy nothing else matches but plays a narrower range and needs more space and breaks. Many couples book a band for the reception and a DJ for ceremony and cocktail hour."),
            ("Is uplighting worth it?",
             "It changes how a room photographs more than almost any other rental at this price. Eight to twelve fixtures around the perimeter does most of the work; you do not need to light everything."),
        ],
    },
    "wedding-bands": {
        "question": 'How much does a wedding band cost?',
        "short": 'wedding band',
        "hook": "Roughly three times a DJ, for something a DJ can't do.",
        "typical": "$2,500-$7,000",
        "answer": "Live wedding bands commonly run $2,500 to $7,000 depending on the number of musicians and how in demand they are. You are paying for something a DJ cannot produce - a room reacting to live music - and giving up range, since a band plays their book rather than any song ever recorded. Many couples split it: band for the reception, DJ or a playlist for ceremony and cocktail hour.",
        "bands": [
            ("Small ensembles", "$1,200-$2,500",
             "Three or four pieces, or a soloist with backing. Excellent for ceremony and cocktail hour, and enough for a smaller reception."),
            ("What most couples pay", "$2,500-$7,000",
             "Six to nine pieces with a front vocalist, their own PA and lighting, typically three 45-minute sets with DJ'd music in between."),
            ("Premium", "$7,000-$20,000+",
             "Ten-plus pieces with horns, multiple vocalists, production and a road crew. At this level you are booking an act, and they are booked a year or more ahead."),
        ],
        "drivers": [
            ("Number of musicians", "The most direct lever - each additional player is typically $300-$600 for the night."),
            ("Reputation and demand", "The best wedding bands in a market are a known quantity and priced accordingly."),
            ("Sets and hours", "Three sets is standard. A fourth, or an early start for the ceremony, costs more."),
            ("Production", "Larger bands bring their own sound and lighting, which is often already in the price - check, because it saves a separate rental."),
            ("Logistics", "Bands need a stage area, power, parking, load-in time and a meal for each musician. Some venues charge for the space they take up."),
            ("Learning your first dance", "Many bands will learn a song not in their book, sometimes for a fee, sometimes free. Ask early."),
        ],
        "save": [
            ("Use the band where it counts",
             "Book them for the reception only and use a DJ or a playlist for ceremony and cocktails. This is the standard way to afford live music."),
            ("Take a smaller line-up of the same band",
             "A seven-piece version of a ten-piece band is often 30% less and, in a room of 120 people, indistinguishable."),
            ("Ask about off-peak rates",
             "Bands discount Fridays, Sundays and winter dates as readily as venues do."),
            ("Confirm what the DJ'd breaks sound like",
             "Some bands provide a proper DJ between sets, others hit play on a phone. It is a third of your reception either way."),
        ],
        "ask": [
            "Can I see unedited footage from a recent wedding, not a produced showreel?",
            "Which musicians in that video are contracted for my date?",
            "Do you bring your own sound and lighting, and what do you need from the venue?",
            "How many sets, how long, and what plays between them?",
            "Will you learn our first dance song, and is there a charge?",
        ],
        "timing": "Nine to fifteen months out. Good bands hold fewer dates than DJs do - there is only one of them and they cannot double-book - so this is a category where being late genuinely closes doors.",
        "faqs": [
            ("How much does a wedding band cost?",
             "Live wedding bands commonly cost $2,500 to $7,000, driven mostly by the number of musicians. Small three or four-piece ensembles start around $1,200; large bands with horns and full production run $7,000 to $20,000 or more."),
            ("Band or DJ - which should we choose?",
             "A band costs roughly three times a DJ and creates energy recorded music cannot, but plays a narrower range of songs. A DJ plays anything, exactly as people know it, and handles announcements. Booking a band for the reception and a DJ for ceremony and cocktail hour is a common compromise."),
            ("How far in advance should we book a wedding band?",
             "Nine to fifteen months. Bands can only play one wedding per date and the well-regarded ones in each market fill early, so this is a booking worth making sooner than you think."),
        ],
    },
    # ---------------------------------------------------------------- food & drink
    "wedding-caterers": {
        "question": 'How much does wedding catering cost?',
        "short": 'wedding caterer',
        "hook": 'Per-guest quotes hide staffing, rentals and service charges.',
        "typical": "$40-$120 per guest",
        "answer": "Wedding catering typically runs $40 to $120 per guest depending on service style - buffet and stations at the lower end, plated service higher. The per-plate number rarely tells the whole story: staffing, rentals, service charges and bar are frequently separate, and can add 30-50% to the figure you were quoted. Ask for a total, for your guest count, with everything in it.",
        "bands": [
            ("Simple service", "$40-$60 per guest",
             "Buffet, family-style, food trucks, or a taco or BBQ setup. Often the food people actually remember, and the easiest place in the whole budget to spend less without anyone noticing."),
            ("What most couples pay", "$60-$100 per guest",
             "Plated dinner or elevated stations, passed appetisers at cocktail hour, full staffing, and often rentals included."),
            ("Premium", "$100-$250+ per guest",
             "Multi-course plated service, premium proteins, chef stations, high staff-to-guest ratios and coursed wine. Common at full-service venues where catering is in-house."),
        ],
        "drivers": [
            ("Service style", "Plated service needs roughly twice the staff of a buffet. This is usually the biggest single difference between two quotes."),
            ("Guest count", "Everything here is per person, which makes the guest list the real catering lever."),
            ("Bar", "Frequently a separate line entirely. Beer and wine only is commonly $15-$25 per guest; a full open bar $25-$60. Consumption-based bars can be cheaper or much more expensive - ask for both quotes."),
            ("Staffing and service charge", "Typically 18-24% on top. Confirm whether it is gratuity or the caterer's operating charge, and whether you are also expected to tip."),
            ("Rentals", "Plates, glassware, flatware, linens and tables may or may not be included. This is $10-$30 per guest when it is not."),
            ("Tastings and dietary requirements", "Tastings are sometimes free, sometimes $75-$200 per person and credited if you book."),
        ],
        "save": [
            ("Change the service style, not the menu",
             "Family-style and stations cost less than plated and feed people better. Nobody has ever complained about a wedding because the food arrived on a platter."),
            ("Shorten the bar rather than closing it",
             "Beer, wine and one signature cocktail covers most guests at a fraction of a full open bar. A cash bar after dinner reads worse than a simpler bar all night."),
            ("Trim cocktail hour, not dinner",
             "Three passed appetisers instead of six is invisible. Two courses instead of three is not."),
            ("Count children and vendors properly",
             "Kids' meals and vendor meals are usually discounted but are frequently left off the first quote - and vendor meals are contractually required more often than couples realise."),
        ],
        "ask": [
            "What is the all-in cost for my guest count, including staffing, rentals, service charge, bar and tax?",
            "Is the service charge gratuity, and if not, what is customary on top?",
            "What are the vendor meal requirements and what do they cost?",
            "Who is the on-site captain and how many staff will be working?",
            "How do you handle allergies and dietary requirements on the night?",
        ],
        "timing": "Book 8-12 months out, or immediately after the venue if the venue requires a caterer from an approved list. Tastings usually happen 3-6 months before the wedding.",
        "faqs": [
            ("How much does wedding catering cost per person?",
             "Wedding catering typically costs $40 to $120 per guest. Buffet and family-style service sits at the lower end, plated dinner at the higher end, and premium multi-course service runs $100 to $250 or more. Bar, rentals and service charges are frequently separate."),
            ("Is a buffet cheaper than a plated dinner?",
             "Usually yes, mainly because plated service requires roughly twice the staff. Family-style and stations land between the two and tend to feed people more generously than a plated course."),
            ("How much should we budget for an open bar?",
             "Beer and wine only is commonly $15 to $25 per guest for the night; a full open bar $25 to $60. Ask for both a package price and a consumption-based estimate, because which is cheaper depends entirely on your guests."),
            ("What is a service charge on a catering quote?",
             "Typically 18-24% added to food and beverage. It is often the caterer's operating charge rather than gratuity, so ask directly whether staff are tipped out of it and what is customary on top."),
        ],
    },
    "wedding-cakes": {
        "question": 'How much does a wedding cake cost?',
        "short": 'wedding cake baker',
        "hook": 'Priced by the slice - and the venue may charge to cut it.',
        "typical": "$500-$1,000",
        "answer": "Wedding cakes are priced by the slice - commonly $4 to $9 - so a cake serving 120 guests usually lands between $500 and $1,000. Detailed sugar work, hand-painting and metallic finishes push the per-slice price up quickly. A common and sensible move is a smaller decorated cake for cutting and photographs, with plain sheet cakes in the kitchen to actually serve the room.",
        "bands": [
            ("Simple", "$3-$5 per slice",
             "Buttercream, clean finishes, minimal decoration. A 100-guest wedding around $300-$500."),
            ("What most couples pay", "$5-$9 per slice",
             "Three tiers, fondant or textured buttercream, fresh florals or moderate sugar work. A 120-guest wedding around $600-$1,000."),
            ("Premium", "$9-$20+ per slice",
             "Hand-painted detail, sculpted sugar flowers, metallic leaf, unusual structures. A showpiece cake can exceed $2,000 on its own."),
        ],
        "drivers": [
            ("Guest count and tiers", "You are buying servings. A dramatic-looking cake for 80 people costs less than a plain one for 250."),
            ("Decoration technique", "Sugar flowers are made by hand, one petal at a time. This is where the price lives, not in the cake."),
            ("Fondant versus buttercream", "Fondant holds sharp edges and costs more; textured buttercream is fashionable and cheaper."),
            ("Fillings and flavours", "Multiple flavours across tiers add cost. Specialty fillings more."),
            ("Delivery and setup", "Typically $50-$150, and worth paying - a tiered cake is not something to transport yourself."),
            ("Cutting fee", "Some venues charge $1-$4 per slice to cut and serve a cake they did not supply. Ask before you order."),
        ],
        "save": [
            ("Display cake plus kitchen sheet cakes",
             "A two-tier decorated cake for the photographs and cutting, with sheet cakes of the same flavour served from the kitchen. Saves 40-60% and no guest ever knows."),
            ("Choose texture over sugar flowers",
             "Textured buttercream with fresh flowers from your florist looks expensive and is not."),
            ("Go smaller, not plainer",
             "A beautiful small cake photographs better than a large dull one."),
            ("Check the cutting fee first",
             "At $3 a slice for 150 guests, the venue's cutting fee can exceed the cake."),
        ],
        "ask": [
            "What is the price per serving, and how many servings am I actually buying?",
            "Is delivery and setup included, and when will you arrive?",
            "Does my venue charge a cutting fee?",
            "Can we taste the exact flavours and fillings we are ordering?",
            "How will the cake hold up in the temperature at my venue?",
        ],
        "timing": "Four to six months out, with tastings around three months. Cakes are among the last vendors you need to book and one of the easiest to arrange late.",
        "faqs": [
            ("How much does a wedding cake cost?",
             "Wedding cakes are usually priced per slice at $4 to $9, so a cake for 120 guests commonly costs $500 to $1,000. Elaborate sugar work and hand-painted detail can push the per-slice price to $20 or more."),
            ("How do we save money on a wedding cake?",
             "Order a smaller decorated cake for cutting and photographs, with plain sheet cakes of the same flavour served from the kitchen. This typically saves 40-60% and guests cannot tell the difference on the plate."),
            ("What is a cake cutting fee?",
             "Some venues charge $1 to $4 per slice to cut and serve a cake they did not supply. On a 150-guest wedding that can cost more than the cake itself, so confirm it before you order."),
        ],
    },
    # ---------------------------------------------------------------- look & feel
    "wedding-florists": {
        "question": 'How much do wedding flowers cost?',
        "short": 'wedding florist',
        "hook": 'Seasonality moves this price more than anything else.',
        "typical": "$1,500-$4,000",
        "answer": "Most couples budget $1,500 to $4,000 for wedding flowers, with bridal bouquets, ceremony pieces and centrepieces as the main drivers. Flowers are the category where the gap between a photograph on Pinterest and a quote is widest, because that photograph usually contains several hundred imported stems. Seasonal, locally available blooms stretch a budget further than any other decision here.",
        "bands": [
            ("Essentials only", "$800-$1,500",
             "Bridal bouquet, a few bridesmaid bouquets, boutonnieres, and simple centrepieces. Enough for the photographs that matter."),
            ("What most couples pay", "$1,500-$4,000",
             "Full personal flowers, a ceremony arrangement or arch, centrepieces for every table, and some additional styling."),
            ("Premium", "$4,000-$15,000+",
             "Installations, hanging arrangements, floral arches, aisle work and full reception design, usually with a team installing on the day."),
        ],
        "drivers": [
            ("Seasonality and origin", "Peonies in October are flown in and priced accordingly. The same look built from what is in season locally is routinely half."),
            ("Stem count, not arrangement count", "A lush centrepiece may hold sixty stems and a simple one twelve. Two quotes for 'ten centrepieces' can differ threefold."),
            ("Installations", "Arches, hanging florals and ceiling work carry labour, hardware and rigging on top of the flowers."),
            ("Labour and delivery", "Wedding florals are made the day before and delivered and installed on the day. A significant share of the cost is people, not plants."),
            ("Repurposing", "Moving ceremony arrangements to the reception is usually free or cheap and effectively doubles what you bought."),
            ("Holidays", "Valentine's Day and Mother's Day move the global flower market. Weddings near them pay more."),
        ],
        "save": [
            ("Give the florist a palette and a budget, not a photograph",
             "Say what you want it to feel like and what you can spend. A good florist will design to the number using what is beautiful that week."),
            ("Repurpose the ceremony flowers",
             "Arrangements from the aisle and the arch can move to the reception, the sweetheart table and the bar. Ask them to plan for it."),
            ("Vary the centrepieces",
             "Alternate a full arrangement with a cluster of bud vases and candles. The room reads as designed and costs meaningfully less."),
            ("Spend on the bouquet",
             "It is in more photographs than anything else you will buy from a florist."),
        ],
        "ask": [
            "What is in season and local around my date, and what would you do with my budget?",
            "Does the quote include delivery, setup, and coming back to strike?",
            "Can any ceremony pieces be moved to the reception, and who moves them?",
            "Who is installing on the day and how long do you need?",
            "What happens if a flower I have chosen is unavailable that week?",
        ],
        "timing": "Six to nine months out, and earlier if you want installations. Final stem counts and numbers are usually confirmed about a month before.",
        "faqs": [
            ("How much do wedding flowers cost?",
             "Most couples budget $1,500 to $4,000 for wedding florals. Essentials-only packages start around $800; full design with installations and hanging arrangements runs $4,000 to $15,000 or more. Seasonality is the single biggest cost factor."),
            ("How can we make a wedding flower budget go further?",
             "Give your florist a colour palette and a budget rather than a specific photograph, so they can use what is in season and local that week. Repurposing ceremony arrangements at the reception, and alternating full centrepieces with bud vases and candles, both stretch the budget without looking sparse."),
            ("Why are wedding flowers so expensive?",
             "A large share of the cost is labour and logistics rather than the flowers themselves - arrangements are built the day before, delivered and installed on the day, and often struck afterwards. Out-of-season blooms are also flown in, which can double the stem price."),
        ],
    },
    "hair-and-makeup": {
        "question": 'How much is bridal hair and makeup?',
        "short": 'hair and makeup artist',
        "hook": 'The cost is predictable. The morning schedule is not.',
        "typical": "$150-$350 for the bride",
        "answer": "Bridal hair and makeup typically runs $150 to $350 for the bride, often including a trial, with bridal-party services around $75 to $150 per person per service. The cost is predictable; the schedule is not. Morning timing is where weddings most commonly run late, so the number of artists matters as much as the price.",
        "bands": [
            ("Bride only", "$150-$350",
             "Hair and makeup for the bride, usually with a trial included or offered at an additional $75-$150."),
            ("Bride and party", "$500-$1,500",
             "Bride plus four to six people having hair, makeup or both. This is where most weddings land."),
            ("Premium / large party", "$1,500-$4,000+",
             "A team of artists on site, airbrush, hair extensions and additions, touch-up attendance through the day, and sometimes a second look for the reception."),
        ],
        "drivers": [
            ("Number of services, not people", "One person having both hair and makeup is two services. A party of six having both is twelve, and that is what sets the schedule and the price."),
            ("Number of artists", "One artist working alone can take six hours for a party of six. Two or three artists compress that dramatically, cost more, and are frequently the difference between a calm morning and a late ceremony."),
            ("Trials", "Commonly $75-$150 each and worth doing for the bride. Trials for the whole party rarely are."),
            ("Travel and early starts", "On-site service usually carries a travel fee, and a start before about 7am often carries an early-call charge."),
            ("Touch-ups and a second look", "An artist staying through the day is typically $75-$150 per hour."),
            ("Airbrush and extensions", "Usually $25-$75 above standard application."),
        ],
        "save": [
            ("Buy more artists, not fewer services",
             "The thing that goes wrong here is time, not quality. A second artist costs less than a delayed ceremony."),
            ("Let the party pay for themselves",
             "It is completely normal for bridesmaids to cover their own hair and makeup. Say so early and kindly."),
            ("Do the trial, skip the party trials",
             "Your trial prevents the one genuinely unrecoverable mistake. Everyone else can be briefed on the day."),
            ("Choose one service for the party",
             "Hair for everyone and makeup for the bride, or the reverse, halves the party cost and the morning."),
        ],
        "ask": [
            "How many artists are coming, and what is the schedule for my party size?",
            "What time do you need to start for us to be ready with buffer?",
            "Is the trial included, and can we do it at the time of day the wedding starts?",
            "Do you stay for touch-ups, and what does that cost?",
            "What is your travel fee and early-start policy?",
        ],
        "timing": "Book 6-9 months out and do the trial 2-3 months before. Ask your artist to build the morning schedule backwards from when photographs start, not from the ceremony.",
        "faqs": [
            ("How much does bridal hair and makeup cost?",
             "Bridal hair and makeup typically costs $150 to $350 for the bride, often including a trial. Bridal-party services run around $75 to $150 per person per service, so a bride plus five attendants having both hair and makeup commonly totals $700 to $1,500."),
            ("Should bridesmaids pay for their own hair and makeup?",
             "It is entirely normal for them to pay their own way, and equally normal for the couple to cover it. What matters is saying which it will be early, before anyone has budgeted around an assumption."),
            ("How long does wedding hair and makeup take?",
             "Roughly 45-75 minutes per service. One artist handling a party of six having both hair and makeup can take six hours or more, which is why booking a second artist is often the difference between a calm morning and a late start."),
        ],
    },
    # ---------------------------------------------------------------- the rest
    "wedding-officiants": {
        "question": 'How much does a wedding officiant cost?',
        "short": 'wedding officiant',
        "hook": 'A small line for the twenty minutes everyone came to watch.',
        "typical": "$300-$800",
        "answer": "Professional wedding officiants commonly charge $300 to $800, typically including a planning meeting, a personalised ceremony script, and rehearsal attendance at the higher tiers. It is a small line in a wedding budget for the twenty minutes that everyone came to watch - and the one part of the day where a weak choice is impossible to hide.",
        "bands": [
            ("Simple ceremony", "$150-$350",
             "A short, largely standard ceremony, often with a brief phone consultation. Fine for a courthouse-style or very small wedding."),
            ("What most couples pay", "$350-$800",
             "A planning meeting, a ceremony written around your story, coordination with your venue, and attendance at the rehearsal."),
            ("Premium", "$800-$2,000+",
             "Multiple meetings, bilingual or interfaith ceremonies, significant custom writing, and well-known officiants in demand."),
        ],
        "drivers": [
            ("Customisation", "A ceremony written from interviews with both of you is a different job from a template with your names in it."),
            ("Rehearsal attendance", "Frequently a separate $100-$200. Worth it if your processional is at all complicated."),
            ("Religious or cultural requirements", "Interfaith, bilingual, or tradition-specific ceremonies - including a lazo, arras or veil ceremony - take more preparation."),
            ("Travel", "Standard beyond a local radius."),
            ("Legal paperwork", "Filing the licence is usually included, but confirm it - it is the one part that has to be right."),
        ],
        "save": [
            ("Have someone you love get ordained",
             "Genuinely free and often more moving, but understand what you are taking on: they will need help writing it, a rehearsal, and someone confirming your state's rules on who may solemnise."),
            ("Take the package without the rehearsal",
             "If your ceremony is simple and your coordinator is running the rehearsal, you may not need the officiant there."),
            ("Book a newer officiant",
             "This is a category where enthusiasm and preparation matter more than years, and where you can hear the whole product in advance."),
        ],
        "ask": [
            "Can I read a ceremony you have written, or watch one you have performed?",
            "How much of the ceremony is written for us, and when do we see a draft?",
            "Are you comfortable including our cultural or religious traditions?",
            "Do you attend the rehearsal, and is that included?",
            "Who files the marriage licence, and by when?",
        ],
        "timing": "Four to eight months out is comfortable. If you want a specific well-known officiant, or you need an interfaith or bilingual ceremony, start earlier.",
        "faqs": [
            ("How much does a wedding officiant cost?",
             "Professional officiants commonly charge $300 to $800, typically including a planning meeting, a personalised ceremony script and rehearsal attendance at the higher tiers. Simple ceremonies start near $150; highly customised, bilingual or interfaith ceremonies can run $800 to $2,000."),
            ("Can a friend or family member officiate our wedding?",
             "In most of the United States a friend can be ordained online and legally solemnise your marriage, though the rules vary by state and a few counties have additional requirements. Check your county clerk's rules first, and give them real help with writing and a rehearsal."),
            ("What should we ask a wedding officiant before booking?",
             "Ask to read a ceremony they have written or watch one they have performed, how much is customised for you and when you will see a draft, whether they attend the rehearsal, and who is responsible for filing the marriage licence."),
        ],
    },
    "wedding-transportation": {
        "question": 'How much does wedding transportation cost?',
        "short": 'transportation company',
        "hook": 'Three-hour minimums, even for a twenty-minute drive.',
        "typical": "$400-$1,200",
        "answer": "Wedding transportation typically runs $400 to $1,200 depending on the vehicle and the hours, with classic cars and limousines usually carrying three or four-hour minimums. Most couples underspend here and then discover that moving 120 guests between a ceremony and a reception is a logistics problem, not a style choice.",
        "bands": [
            ("Couple only", "$300-$700",
             "A car for the two of you between venues and away at the end. Usually a three-hour minimum whether you need three hours or not."),
            ("What most couples pay", "$700-$1,500",
             "A vehicle for the couple plus a shuttle or party bus for the wedding party, or a guest shuttle running between hotel and venue."),
            ("Full guest transport", "$1,500-$5,000+",
             "Multiple shuttles running loops for all guests across the evening, common at venues with limited parking or where guests are drinking."),
        ],
        "drivers": [
            ("Hourly minimums", "Three to four hours is standard even for a twenty-minute journey, and the clock often starts at the depot."),
            ("Vehicle type", "A sedan, a stretch limousine, a vintage car and a 40-seat coach are four different prices for the same twenty minutes."),
            ("Number of runs", "A shuttle doing three loops is priced very differently from one doing a single transfer."),
            ("Late-night returns", "The end-of-night run is where most couples add cost, and it is usually the one guests most need."),
            ("Peak Saturdays", "Prom season and peak wedding Saturdays genuinely sell out the local fleet."),
            ("Gratuity", "Frequently added automatically at 18-20%."),
        ],
        "save": [
            ("Shuttle guests, not yourselves",
             "If you have to choose, moving guests safely matters more than arriving in something photogenic."),
            ("Run loops instead of one big coach",
             "A smaller vehicle doing three trips often costs less than a coach doing one, and starts the party earlier for whoever is on it."),
            ("Skip the getaway car",
             "It is a lovely photograph and a full hourly minimum."),
            ("Use a rideshare arrangement for the late run",
             "Some venues and hotels will coordinate a rideshare code instead of a contracted late shuttle."),
        ],
        "ask": [
            "What is the minimum, and when does the clock start - at pickup or at the depot?",
            "Is gratuity included, and at what rate?",
            "What is the backup if a vehicle breaks down on the day?",
            "Can the vehicle actually access my venue - low bridges, narrow lanes, parking?",
            "How many runs are included, and what does an extra late-night loop cost?",
        ],
        "timing": "Four to eight months out, and earlier for peak Saturdays or if you need a specific vintage vehicle - most operators own only one.",
        "faqs": [
            ("How much does wedding transportation cost?",
             "Wedding transportation typically costs $400 to $1,200 for the couple and wedding party, with three or four-hour minimums common. Full guest shuttles running multiple loops across the evening run $1,500 to $5,000 or more depending on vehicle size and number of runs."),
            ("Do we need to provide transportation for guests?",
             "You are not obliged to, but it matters most where parking is limited, the venue is remote, or you are serving alcohol and guests would otherwise drive. A shuttle between the hotel and venue is one of the more appreciated things couples pay for."),
            ("How long do we need to book a wedding car for?",
             "Most operators have a three or four-hour minimum regardless of how long the journey takes, and the clock frequently starts when the vehicle leaves the depot rather than when it reaches you. Ask which, because it changes the real cost."),
        ],
    },
    "wedding-rentals": {
        "question": 'How much do wedding rentals cost?',
        "short": 'rental company',
        "hook": 'Delivery and setup are often a separate line entirely.',
        "typical": "$1,500-$5,000",
        "answer": "Rental budgets vary enormously with guest count and design - many couples land between $1,500 and $5,000 covering tables, chairs, linens and tableware. The trap in this category is that delivery, setup and strike are frequently separate line items, so two quotes that look comparable often are not. Always compare delivered-and-installed totals.",
        "bands": [
            ("Gap-filling", "$500-$1,500",
             "Your venue includes most things and you are adding linens, some glassware, or a few lounge pieces."),
            ("What most couples pay", "$1,500-$5,000",
             "Tables, chairs, linens, china, glassware and flatware for 100-150 guests, delivered and set."),
            ("Full build", "$5,000-$30,000+",
             "A tent or marquee, flooring, lighting, power, climate control, restrooms and everything inside. Effectively building a venue on an empty site."),
        ],
        "drivers": [
            ("Guest count", "Every place setting is a chair, a linen, a plate, three glasses and flatware. The list scales exactly with the list."),
            ("Whether the site has anything", "A bare field needs power, flooring, lighting and restrooms before a single table arrives. This is the difference between a $3,000 rental order and a $25,000 one."),
            ("Delivery, setup and strike", "Often 15-25% of the order, sometimes more for a difficult site or an overnight strike."),
            ("Upgrade tiers", "Chiavari chairs instead of folding chairs, or a specialty linen instead of standard, is typically $4-$12 per guest each."),
            ("Tents", "Priced by size, sidewalls, flooring and lighting - and a tent almost always brings power and climate control with it."),
            ("Peak weekends", "Inventory is finite locally. On a busy Saturday the item you want may simply not exist within a hundred miles."),
        ],
        "save": [
            ("Choose a venue that includes things",
             "A venue $2,000 more expensive that includes tables, chairs, linens and china is usually cheaper overall. This decision is made before you ever talk to a rental company."),
            ("Upgrade the chairs, not everything",
             "Chairs are in every wide photograph. Flatware is in none."),
            ("Consolidate suppliers",
             "One order delivered once beats three orders delivered three times, each with its own fee."),
            ("Confirm what the caterer brings",
             "Caterers frequently include china, glassware and flatware. Couples routinely rent these twice."),
        ],
        "ask": [
            "Can I have the total delivered, set up and struck, not just the item prices?",
            "What does my caterer already provide so I do not rent it twice?",
            "When do you deliver and collect, and does the venue allow those times?",
            "What happens if something arrives damaged or short on the day?",
            "Is there a replacement charge for breakages, and at what rate?",
        ],
        "timing": "Six to nine months out, and much earlier for tents and anything on a bare site. Final counts are usually adjustable until 2-3 weeks before.",
        "faqs": [
            ("How much do wedding rentals cost?",
             "Most couples spend $1,500 to $5,000 on rentals covering tables, chairs, linens and tableware for 100-150 guests. Building on a bare site with a tent, flooring, lighting, power and restrooms runs $5,000 to $30,000 or more."),
            ("Are delivery and setup included in rental quotes?",
             "Frequently not. Delivery, setup and strike commonly add 15-25% to an order and are often listed separately, so always compare quotes on the delivered-and-installed total rather than the item prices."),
            ("What do wedding caterers usually provide?",
             "Many caterers include china, glassware, flatware and sometimes linens in their pricing. Confirm exactly what is covered before placing a rental order, because renting these twice is one of the most common wedding budget mistakes."),
        ],
    },
    "wedding-invitations": {
        "question": 'How much do wedding invitations cost?',
        "short": 'stationer',
        "hook": 'Printing method sets the price; weigh one before buying stamps.',
        "typical": "$400-$1,500",
        "answer": "Couples typically spend $400 to $1,500 on invitation suites, driven mostly by printing method - digital printing at the lower end, letterpress and foil above it. The suite is the first thing your guests physically hold and the only part of the wedding that arrives before the wedding, which is why it is worth more attention than its share of the budget suggests.",
        "bands": [
            ("Digital printing", "$250-$600",
             "Flat-printed invitations, an RSVP card and envelopes for 80-100 households. Modern digital printing is genuinely good, and this is where most of the value in this category sits."),
            ("What most couples pay", "$600-$1,500",
             "A fuller suite - invitation, details card, RSVP, envelope liners, perhaps a vellum wrap or wax seal - with some specialty finishing."),
            ("Premium", "$1,500-$6,000+",
             "Letterpress or engraving, foil, custom illustration, handmade paper, calligraphed addressing, and a designer working bespoke."),
        ],
        "drivers": [
            ("Printing method", "Digital, thermography, letterpress, engraving and foil form a clear price ladder. Letterpress typically triples the cost of digital."),
            ("Number of pieces", "An invitation, details card, RSVP and two envelopes is five printed items per household, not one."),
            ("Quantity", "Priced per household, not per guest - roughly 60% of your guest count. Order 10-15% extra for mistakes and keepsakes; a reprint run costs far more than extras did."),
            ("Addressing", "Calligraphy is commonly $2-$6 per envelope. Printed addressing is a fraction and looks excellent."),
            ("Postage", "Genuinely overlooked. Square, thick or oversized suites need extra postage, sometimes double. Weigh a finished suite before buying stamps."),
            ("Save-the-dates and day-of paper", "Menus, programmes, place cards, signage and thank-you cards are a second order most couples forget to budget."),
        ],
        "save": [
            ("Use digital printing and spend on paper",
             "Heavy, beautiful stock digitally printed reads more expensive than thin letterpress."),
            ("Cut pieces, not quality",
             "A single invitation with a QR code to your wedding website replaces a details card and an RSVP card, and most guests prefer it."),
            ("Print the addressing",
             "At 100 households, calligraphy can cost more than the invitations."),
            ("Weigh one before you buy postage",
             "A sample suite at the post office costs nothing and prevents the most annoying surprise in this category."),
        ],
        "ask": [
            "What is the total for my household count including envelopes, addressing and shipping?",
            "Can I see and feel a physical sample of this stock and printing method?",
            "How many extras are included, and what does a small reprint cost?",
            "What does a finished suite weigh, and what postage will it need?",
            "What is the timeline from final proof to delivery?",
        ],
        "timing": "Start 4-5 months before the wedding. Invitations go out 6-8 weeks ahead (three months for destination weddings), and save-the-dates six to eight months ahead.",
        "faqs": [
            ("How much do wedding invitations cost?",
             "Most couples spend $400 to $1,500 on invitation suites. Digital printing for 80-100 households starts around $250; letterpress, foil and engraving with custom illustration run $1,500 to $6,000 or more."),
            ("How many wedding invitations do we need?",
             "Order by household, not by guest - roughly 60% of your guest count, plus 10-15% extra for addressing mistakes and keepsakes. Reprint runs are disproportionately expensive, so extras are cheap insurance."),
            ("When should we send wedding invitations?",
             "Six to eight weeks before the wedding for local guests, and about three months ahead for destination weddings. Save-the-dates go out six to eight months before."),
        ],
    },
    "day-of-coordination": {
        "question": 'How much does day-of coordination cost?',
        "short": 'coordinator',
        "hook": 'The cheapest tier of planning, and the least regretted.',
        "typical": "$800-$2,000",
        "answer": "Day-of coordination commonly runs $800 to $2,000 - and the name is misleading in a way that matters. A good coordinator starts four to six weeks before the wedding: confirming every vendor, building the timeline, and running the rehearsal and the day itself. It is the cheapest tier of wedding planning and the one couples most often say they would not have gone without.",
        "bands": [
            ("Minimal", "$500-$800",
             "Someone present on the day to execute a timeline you wrote. Better than nothing, but you are still doing the coordination."),
            ("What most couples pay", "$800-$2,000",
             "A month-out handover: vendor confirmations, a built timeline, a rehearsal run, a full wedding day on site, and managing setup and strike."),
            ("Premium / complex", "$2,000-$4,000+",
             "Two coordinators or a coordinator plus assistants, multi-day events, or weddings with complicated logistics across sites."),
        ],
        "drivers": [
            ("When they actually start", "Four to six weeks out versus the morning of is the entire difference in this category. Ask directly."),
            ("Guest count and venue complexity", "Two hundred guests, two locations, or a bare site all need more hands."),
            ("Team size", "An assistant is typically $300-$600 and is what allows one person to be at the ceremony while another sets the reception."),
            ("Hours on the day", "Most packages cover 10-12 hours. Setup starting at 8am and strike ending at midnight exceeds that."),
            ("Rehearsal attendance", "Usually included at this tier, but confirm."),
        ],
        "save": [
            ("This is the saving",
             "Coordination is the line that protects every other line. The alternative is not saving $1,200 - it is your mother or your maid of honour working your wedding instead of attending it."),
            ("Check the venue's offer honestly",
             "Some venues include real coordination. Most include a building manager. Ask what they do about your florist being late, and listen to the answer."),
            ("Take the single coordinator if the day is simple",
             "Under 100 guests at one venue rarely needs a second person."),
            ("Do your own design",
             "Coordination does not include styling. If you have that covered, you do not need to move up a tier."),
        ],
        "ask": [
            "When exactly do you take over, and what happens between now and then?",
            "Do you contact and confirm all of my vendors, or do I?",
            "How many hours on the day, and does that cover setup and strike?",
            "Will you run the rehearsal?",
            "How many weddings do you have that weekend, and who is my backup?",
        ],
        "timing": "Four to eight months out. Coordinators book later than full-service planners, but the well-regarded ones in each market still fill peak Saturdays a year ahead.",
        "faqs": [
            ("How much does day-of wedding coordination cost?",
             "Day-of coordination commonly costs $800 to $2,000. Minimal execute-only service starts around $500; complex weddings needing multiple coordinators run $2,000 to $4,000 or more."),
            ("What does a day-of coordinator actually do?",
             "Despite the name, most begin four to six weeks before the wedding - confirming every vendor, building and distributing a timeline, running the rehearsal, then managing setup, the day itself and strike. They are the reason nobody in your family has to work your wedding."),
            ("Do we need a coordinator if our venue has one?",
             "Often yes. A venue coordinator is responsible for the venue - its staff, its spaces, its rules. A day-of coordinator is responsible for your wedding across every vendor. Ask the venue what they do if your florist arrives late, and judge from the answer."),
        ],
    },
}
